version: "3.2"

services:
  breathecode:
    image: geeksacademy/breathecode:development
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    environment:
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=postgres://user:pass@postgres:5432/breathecode
      - CELERY_DISABLE_SCHEDULER=
      - ALLOW_UNSAFE_CYPRESS_APP=True
    depends_on:
      - postgres
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=breathecode

  adminer:
    image: adminer
    ports:
      - 8080:8080
    depends_on:
      - postgres

volumes:
  postgres_data:
